language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install dataclasses; fi

script:
    - python -m pytest -v .