language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

script:
    - python -m pytest -v .